sudo: false
language: elixir

elixir: '1.9'
otp_release: '22.0'

stages:
  - check formatted
  - test

jobs:
  include:
    - stage: check formatted
      script: mix format --check-formatted

    - stage: test

    - elixir: 1.5
      otp_release: 19.3
    - elixir: 1.5
      otp_release: 20.3
    - elixir: 1.9
      otp_release: 20.3
    - elixir: 1.9
      otp_release: 21.3
